# Generated by Django 2.2.7 on 2019-12-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
